development:
  adapter: postgresql
  encoding: unicode
  database: juice_development
  pool: 5
  username: juice
  password: juice
  host: localhost
  port: 5432

test: &test
  adapter: postgresql
  encoding: unicode
  database: juice_test
  pool: 5
  username: juice
  password: juice
  host: localhost
  port: 5432

cucumber:
  <<: *test